'user strict';

import * as Colors from 'material-ui/styles/colors';
import Spacing from 'material-ui/styles/spacing';
import zIndex from 'material-ui/styles/zIndex';

export default {
  spacing: Spacing,
  zIndex: zIndex,
  fontFamily: 'Quattrocento, sans-serif',
  palette: {
    primary1Color: Colors.blue900,
    primary2Color: Colors.blue700,
    primary3Color: Colors.blue50,
    accent1Color: Colors.blueGrey600,
    accent2Color: Colors.blueGrey400,
    accent3Color: Colors.blueGrey100,
    textColor: Colors.blue900,
    alternateTextColor: Colors.white,
    canvasColor: Colors.white,
    borderColor: Colors.grey300,
    pickerHeaderColor: Colors.blue900,
  }
};

// /* Palette generated by Material Palette - materialpalette.com/cyan/grey */

// .dark-primary-color    { background: #0097A7; }
// .default-primary-color { background: #00BCD4; }
// .light-primary-color   { background: #B2EBF2; }
// .text-primary-color    { color: #FFFFFF; }
// .accent-color          { background: #9E9E9E; }
// .primary-text-color    { color: #212121; }
// .secondary-text-color  { color: #757575; }
// .divider-color         { border-color: #BDBDBD; }

